browser.name=Chrome

#DEV Environment credentials
app.dev.url=https://www.myntra.com/
app.dev.mobileNO=9370561429

#QA Environment credentials
app.qa.url=https://www.myntra.com/
app.qa.mobileNO=9370561429


